/*
 XSDelement.h
 The interface definition of properties and methods for the XSDelement object.
 Generated by SudzC.com
 */


#import "XSSchemaNode.h"

@class XSDcomplexType;
@protocol XSType;

@interface XSDelement : XSSchemaNode

@property (readonly, nonatomic) id<XSType> localType;
@property (readonly, nonatomic) NSString* name;
@property (readonly, nonatomic) NSString* ref;
@property (readonly, nonatomic) NSString* type;
@property (readonly, nonatomic) NSString* substitutionGroup;
@property (readonly, nonatomic) NSString* defaultValue;
@property (readonly, nonatomic) NSString* fixed;
@property (readonly, nonatomic) NSNumber* nillable;
@property (readonly, nonatomic) NSNumber* abstract;
@property (readonly, nonatomic) NSString* finalValue;
@property (readonly, nonatomic) NSString* block;
@property (readonly, nonatomic) NSString* form;
@property (readonly, nonatomic) NSNumber* minOccurs;
@property (readonly, nonatomic) NSNumber* maxOccurs;

- (instancetype) initWithNode:(NSXMLElement*)node schema:(XSDschema*)schema minOccurs:(NSNumber *)minOccurs maxOccurs:(NSNumber *)maxOccurs;

- (NSString*) readCodeForContent;
- (NSString*) writeCodeForContent;
- (NSString*) variableName; //in generated code

- (BOOL) isOptional;
- (BOOL) isRequired;

- (BOOL) isSingleValue;

- (id<XSType>) schemaType;
- (BOOL) hasEnumeration;
- (NSString*) codeType;
- (BOOL) hasAny;

@end
